# fluentd/conf/fluent.conf

<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter **>
  @type record_transformer
  enable_ruby true
  <record>
    hostname "#{Socket.gethostname}"
    service ${tag}
  </record>
</filter>

<match **>
  @type elasticsearch
  host "#{ENV['ES_HOST']}"
  port "#{ENV['ES_PORT']}"
  scheme "#{ENV['ES_SCHEME']}"
  
  logstash_format true
  logstash_prefix fluentd
  type_name _doc
  
  buffer_chunk_limit 10M
  buffer_queue_limit 32
  flush_interval 5s
  max_retry_wait 30
  disable_retry_limit
  
  @log_level warn
</match>

<match fluent.**>
  @type null
</match>

<match fluentd.*>
  @type file
  path /var/log/fluentd/fluentd
  compress gzip
  <buffer>
    @type file
    path /var/log/fluentd/buffer
    chunk_limit_size 10M
    total_limit_size 50M
    flush_mode interval
    flush_interval 5s
  </buffer>
  <format>
    @type json
  </format>
</match>